//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRule) DeepCopyInto(out *ClusterVMHostRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRule.
func (in *ClusterVMHostRule) DeepCopy() *ClusterVMHostRule {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVMHostRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleInitParameters) DeepCopyInto(out *ClusterVMHostRuleInitParameters) {
	*out = *in
	if in.AffinityHostGroupName != nil {
		in, out := &in.AffinityHostGroupName, &out.AffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.AntiAffinityHostGroupName != nil {
		in, out := &in.AntiAffinityHostGroupName, &out.AntiAffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleInitParameters.
func (in *ClusterVMHostRuleInitParameters) DeepCopy() *ClusterVMHostRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleList) DeepCopyInto(out *ClusterVMHostRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterVMHostRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleList.
func (in *ClusterVMHostRuleList) DeepCopy() *ClusterVMHostRuleList {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVMHostRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleObservation) DeepCopyInto(out *ClusterVMHostRuleObservation) {
	*out = *in
	if in.AffinityHostGroupName != nil {
		in, out := &in.AffinityHostGroupName, &out.AffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.AntiAffinityHostGroupName != nil {
		in, out := &in.AntiAffinityHostGroupName, &out.AntiAffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleObservation.
func (in *ClusterVMHostRuleObservation) DeepCopy() *ClusterVMHostRuleObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleParameters) DeepCopyInto(out *ClusterVMHostRuleParameters) {
	*out = *in
	if in.AffinityHostGroupName != nil {
		in, out := &in.AffinityHostGroupName, &out.AffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.AntiAffinityHostGroupName != nil {
		in, out := &in.AntiAffinityHostGroupName, &out.AntiAffinityHostGroupName
		*out = new(string)
		**out = **in
	}
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleParameters.
func (in *ClusterVMHostRuleParameters) DeepCopy() *ClusterVMHostRuleParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleSpec) DeepCopyInto(out *ClusterVMHostRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleSpec.
func (in *ClusterVMHostRuleSpec) DeepCopy() *ClusterVMHostRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMHostRuleStatus) DeepCopyInto(out *ClusterVMHostRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMHostRuleStatus.
func (in *ClusterVMHostRuleStatus) DeepCopy() *ClusterVMHostRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterVMHostRuleStatus)
	in.DeepCopyInto(out)
	return out
}
