apiVersion: file.disashop.com/v1alpha1
kind: File
metadata:
  annotations:
    meta.upbound.io/example-id: file/v1alpha1/file
  labels:
    testing.upbound.io/example-name: ubuntu_vmdk_upload
  name: ubuntu-vmdk-upload
spec:
  forProvider:
    createDirectories: true
    datacenter: dc-01
    datastore: datastore-01
    destinationFile: /my/dst/path/custom_ubuntu.vmdk
    sourceFile: /my/src/path/custom_ubuntu.vmdk
