apiVersion: hostportgroup.disashop.com/v1alpha1
kind: PortGroup
metadata:
  annotations:
    meta.upbound.io/example-id: hostportgroup/v1alpha1/portgroup
  labels:
    testing.upbound.io/example-name: pg
  name: pg
spec:
  forProvider:
    hostSystemId: ${data.vsphere_host.host.id}
    virtualSwitchName: ${vsphere_host_virtual_switch.host_virtual_switch.name}
