apiVersion: contentlibrary.disashop.com/v1alpha1
kind: Library
metadata:
  annotations:
    meta.upbound.io/example-id: contentlibrary/v1alpha1/library
  labels:
    testing.upbound.io/example-name: publisher_content_library
  name: publisher-content-library
spec:
  forProvider:
    description: A publishing content library.
    name: Publisher Content Library
    storageBacking:
    - ${data.vsphere_datastore.publisher_datastore.id}
