// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/edalonso/provider-vsphere-upjet/apis/datacenter/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Host.
func (mg *Host) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Datacenter),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.DatacenterRef,
		Selector:     mg.Spec.ForProvider.DatacenterSelector,
		To: reference.To{
			List:    &v1alpha1.DatacenterList{},
			Managed: &v1alpha1.Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Datacenter")
	}
	mg.Spec.ForProvider.Datacenter = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DatacenterRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Datacenter),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.DatacenterRef,
		Selector:     mg.Spec.InitProvider.DatacenterSelector,
		To: reference.To{
			List:    &v1alpha1.DatacenterList{},
			Managed: &v1alpha1.Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Datacenter")
	}
	mg.Spec.InitProvider.Datacenter = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DatacenterRef = rsp.ResolvedReference

	return nil
}
