apiVersion: vmfsdatastore.disashop.com/v1alpha1
kind: Datastore
metadata:
  annotations:
    meta.upbound.io/example-id: vmfsdatastore/v1alpha1/datastore
  labels:
    testing.upbound.io/example-name: datastore
  name: datastore
spec:
  forProvider:
    disks:
    - mpx.vmhba1:C0:T1:L0
    - mpx.vmhba1:C0:T2:L0
    - mpx.vmhba1:C0:T2:L0
    hostSystemId: ${data.vsphere_host.host.id}
    name: terraform-test
