apiVersion: datastoreclustervmantiaffinityrule.disashop.com/v1alpha1
kind: ClusterVMAntiAffinityRule
metadata:
  annotations:
    meta.upbound.io/example-id: datastoreclustervmantiaffinityrule/v1alpha1/clustervmantiaffinityrule
  labels:
    testing.upbound.io/example-name: cluster_vm_anti_affinity_rule
  name: cluster-vm-anti-affinity-rule
spec:
  forProvider:
    datastoreClusterId: ${data.vsphere_datastore_cluster.datastore_cluster.id}
    name: terraform-test-datastore-cluster-vm-anti-affinity-rule
    virtualMachineIds:
    - ${vsphere_virtual_machine.vm.*.id}

---

apiVersion: virtualmachine.disashop.com/v1alpha1
kind: Machine
metadata:
  annotations:
    meta.upbound.io/example-id: datastoreclustervmantiaffinityrule/v1alpha1/clustervmantiaffinityrule
  labels:
    testing.upbound.io/example-name: vm
  name: vm
spec:
  forProvider:
    count: 2
    datastoreClusterId: ${data.vsphere_datastore_cluster.datastore_cluster.id}
    disk:
    - label: disk0
      size: 20
    guestId: otherLinux64Guest
    memory: 2048
    name: terraform-test-${count.index}
    networkInterface:
    - networkId: ${data.vsphere_network.network.id}
    numCpus: 2
    resourcePoolId: ${data.vsphere_compute_cluster.cluster.resource_pool_id}
