//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRule) DeepCopyInto(out *ClusterVMDependencyRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRule.
func (in *ClusterVMDependencyRule) DeepCopy() *ClusterVMDependencyRule {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVMDependencyRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleInitParameters) DeepCopyInto(out *ClusterVMDependencyRuleInitParameters) {
	*out = *in
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.DependencyVMGroupName != nil {
		in, out := &in.DependencyVMGroupName, &out.DependencyVMGroupName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleInitParameters.
func (in *ClusterVMDependencyRuleInitParameters) DeepCopy() *ClusterVMDependencyRuleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleList) DeepCopyInto(out *ClusterVMDependencyRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterVMDependencyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleList.
func (in *ClusterVMDependencyRuleList) DeepCopy() *ClusterVMDependencyRuleList {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterVMDependencyRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleObservation) DeepCopyInto(out *ClusterVMDependencyRuleObservation) {
	*out = *in
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.DependencyVMGroupName != nil {
		in, out := &in.DependencyVMGroupName, &out.DependencyVMGroupName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleObservation.
func (in *ClusterVMDependencyRuleObservation) DeepCopy() *ClusterVMDependencyRuleObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleParameters) DeepCopyInto(out *ClusterVMDependencyRuleParameters) {
	*out = *in
	if in.ComputeClusterID != nil {
		in, out := &in.ComputeClusterID, &out.ComputeClusterID
		*out = new(string)
		**out = **in
	}
	if in.DependencyVMGroupName != nil {
		in, out := &in.DependencyVMGroupName, &out.DependencyVMGroupName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mandatory != nil {
		in, out := &in.Mandatory, &out.Mandatory
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.VMGroupName != nil {
		in, out := &in.VMGroupName, &out.VMGroupName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleParameters.
func (in *ClusterVMDependencyRuleParameters) DeepCopy() *ClusterVMDependencyRuleParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleSpec) DeepCopyInto(out *ClusterVMDependencyRuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleSpec.
func (in *ClusterVMDependencyRuleSpec) DeepCopy() *ClusterVMDependencyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVMDependencyRuleStatus) DeepCopyInto(out *ClusterVMDependencyRuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVMDependencyRuleStatus.
func (in *ClusterVMDependencyRuleStatus) DeepCopy() *ClusterVMDependencyRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterVMDependencyRuleStatus)
	in.DeepCopyInto(out)
	return out
}
